name: Sync tracker/dev to dev
on:
  push:
    branches: [dev]
  workflow_dispatch: {}
  schedule:
    - cron: '0 */6 * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update branch
        run: |
          git fetch origin dev tracker/dev
          git checkout tracker/dev
          git reset --hard origin/dev
          git push origin tracker/dev --force-with-lease

